packages:
  - apps/*

catalog:
  '@antfu/eslint-config': ^8.2.0
  '@eslint-react/eslint-plugin': ^5.7.5
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-tabs': ^1.1.13
  '@tailwindcss/vite': ^4.3.0
  '@tauri-apps/api': ^2.11.0
  '@tauri-apps/cli': ^2.11.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.12.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^10.2.1
  eslint-plugin-react-refresh: ^0.5.2
  jsdom: ^27.3.0
  lucide-react: ^1.14.0
  react: ^19.2.5
  react-dom: ^19.2.5
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.3.0
  typescript: ~6.0.2
  vite: ^8.0.10
  vitest: ^4.0.16
